# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger: 
  branches:
    include: 
    - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  # This makes the variables available to all of our tasks
  SAUCE_USERNAME: $(sauceUsername)
  SAUCE_ACCESS_KEY: $(sauceKey)

steps:
- task: NuGetToolInstaller@1
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- bash: echo $(SAUCE_USERNAME)
- task: DotNetCoreCLI@2
  displayName: 'Run desktop tests'
  inputs:
    command: test
    projects: '**DotnetCore/Sauce.Demo/*.csproj'
    arguments: '--configuration $(buildConfiguration) --filter TestCategory=desktop'
  # Can also reference env variables in a single task
  env:
    SAUCE_USERNAME: $(sauceUsername)
    SAUCE_ACCESS_KEY: $(sauceKey)
